# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a80d353dff476380b883075097bdb668005fbda69de1b15bb325d5406c5b8d11cff46e04d12c7bc5cb39d00a49e71624fa4cf75e2d0c3ba90b9968caf98ee48

test:
  secret_key_base: 2c7ebd0a6cf6b67cef4c1ee150181593ddeb6d1cf59c4153cdd0e466f9b70e1fd61d46b56243d043b88a60989b51aac76948d4efeb106169ba2461e61899fd3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
